name: nids_lab
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py38h06a4308_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1l=h7f8727e_0
  - python=3.8.12=h12debd9_0
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py38h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - argon2-cffi==21.1.0
    - attrs==21.2.0
    - backcall==0.2.0
    - bleach==4.1.0
    - cffi==1.15.0
    - cycler==0.11.0
    - debugpy==1.5.1
    - decorator==5.1.0
    - defusedxml==0.7.1
    - entrypoints==0.3
    - fonttools==4.28.3
    - importlib-resources==5.4.0
    - ipykernel==6.5.1
    - ipython==7.30.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.1
    - joblib==1.1.0
    - jsonschema==4.2.1
    - jupyter==1.0.0
    - jupyter-client==7.1.0
    - jupyter-console==6.4.0
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.3.2
    - matplotlib==3.5.0
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclient==0.5.9
    - nbconvert==6.3.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.6
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - pip==21.3.1
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.23
    - ptyprocess==0.7.0
    - pycparser==2.21
    - pygments==2.10.0
    - pyparsing==3.0.6
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pyzmq==22.3.0
    - qtconsole==5.2.1
    - qtpy==1.11.2
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - send2trash==1.8.0
    - setuptools-scm==6.3.2
    - sklearn==0.0
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - tomli==1.2.2
    - torch==1.10.0
    - tornado==6.1
    - traitlets==5.1.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.2
    - zipp==3.6.0
prefix: /home/laurens/anaconda3/envs/nids_lab
